# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'GehaSajang' do

  use_frameworks!
  pod 'TextFieldEffects'
  pod 'Hero'
  pod 'SwiftLint'
  pod 'DZNEmptyDataSet'
  pod 'Then'
  pod 'FSCalendar'
  pod 'SnapKit', '~> 5.0.0'
  pod 'BEMCheckBox'


end